apiVersion: v1
kind: Service
metadata:
  namespace: jokeapi
  name: joke-database-svc
  labels:
    app: joke-database
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: joke-database