apiVersion: batch/v1
kind: CronJob
metadata:
  name: job-request-joke
  namespace: jokeapi
spec:
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: job-request-joke
            image: joke-job-request:k8s
            imagePullPolicy: Never
            env:
            - name: POSTGRES_URL
              value: postgresql://admin123:admin123@joke-database-svc/prod
          restartPolicy: OnFailure