apiVersion: v1
kind: Pod
metadata:
  name: nginx-init
  labels:
    app: nginx-init
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  initContainers:
  - name: wait-for-dns
    image: busybox:1.28
    command: ['sh', '-c', 'until nslookup mymysql; do echo waiting for mymysql; sleep 2; done;']

# This pod will run in the default namespace and needs to wait for the mymysql service to be available before starting the nginx container.
# kubectl create service mymysql --tcp=80:80

# kubectl apply -f 02-init-container.yaml
# kubectl get pods
# kubectl describe pod nginx-init