apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multicontainer-pod
  name: multicontainer-pod
spec:
  containers:
  - image: httpd
    name: httpd
  - image: alpine
    name: debug
    command: ["sleep", "9999999999999"]

# If I copy this pod definition into /etc/kubernetes/manifests/multicontainer-pod.yaml,
# the kubelet will automatically create this pod on the node.