apiVersion: batch/v1
kind: CronJob
metadata:
  name: job-request-joke
  namespace: jokeapi
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: job-request-joke
            image: gabrielrichter/api_joke_request_to_postgres:1
            imagePullPolicy: IfNotPresent
            env:
            - name: POSTGRES_URL
              value: postgresql://admin123:admin123@joke-database-svc/prod
          restartPolicy: OnFailure