apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jokeapi
  name: joke-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: joke-api
  template:
    metadata:
      labels:
        app: joke-api
    spec:
      containers:
        - name: joke-api
          image: joke-api-python:k8s
          imagePullPolicy: Never
          env:
          - name: POSTGRES_URL
            value: postgresql://admin123:admin123@joke-database-svc/prod
          ports:
            - containerPort: 8000