apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jokeapi
  name: joke-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joke-database
  template:
    metadata:
      labels:
        app: joke-database
    spec:
      volumes:
      - name: joke-pv-data
        persistentVolumeClaim:
          claimName: postgres-pvc
      containers:
        - name: postgres
          image: 'postgres:16'
          imagePullPolicy: IfNotPresent
          env:
          - name: POSTGRES_USER
            value: admin123
          - name: POSTGRES_PASSWORD
            value: admin123
          - name: POSTGRES_DB
            value: prod
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: joke-pv-data