apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: jokeapi
  name: postgres-pv
  labels:
    type: local
    app: joke-database
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/hostdir/postgresql

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: jokeapi
  name: postgres-pvc
  labels:
    app: joke-database
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi