services:

  streamlit_app:
    build: ./streamlit_app
    networks:
      - scylla_cluster_scylla-net
    environment:
      SCYLLA_IP: scylla-node1

  python_data_writer:
    build: ./python_data_writer
    networks:
      - scylla_cluster_scylla-net
    environment:
      SCYLLA_IP: scylla-node1
    
networks:
  scylla_cluster_scylla-net:
    external: true